### ISSUE TITLE
Part size is not supported; minimum allowed 5MiB when using upload_snowball_objects for small objects

### ISSUE THREAD

**Issue by erwin-vanduijnhoven** [minio/minio-py#1332]
Whenever I try to upload a list of snowballobjects where its total size is less than 5MiB I get the following error: 

``` 
part size 425 is not supported; minimum allowed 5MiB
```

This can be easily fixed by setting the part_size to be 5MiB `5 * (1024) ** 2` minimally in the upload_snowball_objects method. https://github.com/minio/minio-py/blob/8e681bba1a78813d25b50949269c26b709d8b2fe/minio/api.py#L2766-L2780

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/1333

**Comment by AboPlus** [comment]
> Fixed by #1333

I saw that you have already fixed this issue. I upgraded the minio-py version to 7.2.2, but the problem still exists. It seems like the code has been fixed. What should I do next in order to validate it?

**Comment by balamurugana** [comment]
Enable `trace_on()` and see what's going on
